services:
  hellojax:
    image: python_image
    container_name: python_container
    volumes:
       - .:/home/docker_user/python_environment
       - ../other_folder:/home/docker_user/other_folder
    tty: true
    # command: nvidia-smi
    deploy:
      resources: 
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]





