services:
  pythonenv:
    image: python/vanilla
    container_name: python_vanilla
    volumes:
       - ..:/home/docker_user/python_environment
       - ../../utlysningsscraper:/home/docker_user/utlysningsscraper
    tty: true






